# Generated by Django 2.2.1 on 2019-05-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
