# Generated by Django 2.2.1 on 2019-05-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_search', '0002_auto_20190524_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
    ]
