# Generated by Django 2.2.1 on 2019-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_search', '0003_auto_20190524_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
