# Generated by Django 2.2.1 on 2019-06-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_search', '0004_auto_20190524_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.CharField(default='hello world', max_length=10000),
            preserve_default=False,
        ),
    ]
