# Generated by Django 2.2.1 on 2019-09-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_search', '0005_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.CharField(max_length=1000),
        ),
    ]
